### ISSUE TITLE
Local tests in a docker?

### ISSUE THREAD

**Issue by theanalyst** [noahdesu/go-ceph#20]
I've a local branch that actually does this, basically run the go tests in a docker container, which has a the simple ceph setup made by micro-osd. The diff is https://github.com/noahdesu/go-ceph/compare/master...theanalyst:docker-ci?expand=1; if this sounds useful I can submit this as a PR

**Comment by noahdesu** [comment]
Thanks! This is cool and I was able to run it. Please submit a pull request.
