### ISSUE TITLE
Omap operations on nonexistent object

### ISSUE THREAD

**Issue by immesys** [noahdesu/go-ceph#31]
I'm not super familiar with the C or C++ versions of librados, so this may be intended behavior but if you attempt to read omap values on a nonexistent object, you get an Input / Output error, not ErrorNotFound:

```golang
func TestOmapReturnedError(t *testing.T) {
	conn, _ := rados.NewConn()
	conn.ReadDefaultConfigFile()
	conn.Connect()
	ioctx, err := conn.OpenIOContext("mypool")
	if err != nil {
		panic(err)
	}
	_, err := ioctx.GetAllOmapValues("def.not.exist", "", "", 100)
	if err != rados.RadosErrorNotFound {
		t.Fatalf("unexpected error code %v", err)
	}
}
```

And I get: `unexpected error code rados: Input/output error`

I generally like to treat object not found errors differently from "can't speak to OSD or MON" errors, and Input/output error is a bit vague. If it is not possible to reliable disambiguate the errors and coerce the type with what librados gives us then feel free to close this, but it bugs me.

**Comment by noahdesu** [comment]
Hi, can you please re-open this issue at github.com/ceph/go-ceph ?

**Comment by immesys** [comment]
Sure, my bad.
